version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis.local

  beat:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - beat.local

  client:
    image: curlimages/curl:latest
    container_name: curl-client
    depends_on:
      - beat
      - redis
    networks:
      default:
    entrypoint: >
      sh -c '
        echo "Attempt $i";
        curl "http://beat:5000/healthcheck";
        curl "http://beat:5000/add_queue?user_id=user1&session_id=11";
        curl "http://beat:5000/add_queue?user_id=user1&session_id=12";
        curl "http://beat:5000/add_queue?user_id=user1&session_id=13";
        curl "http://beat:5000/update_queue?user_id=user1&session_id=11";
        curl "http://beat:5000/update_queue?user_id=user1&session_id=11";
        curl "http://beat:5000/update_queue?user_id=user1&session_id=11";  
        curl "http://beat:5000/update_queue?user_id=user1&session_id=11";
        curl "http://beat:5000/update_queue?user_id=user2&session_id=11";
        curl "http://beat:5000/add_queue?user_id=user1&session_id=14";
        curl "http://beat:5000/add_queue?user_id=user1&session_id=15";
      '

  client2:
    build:
      context: ./client2
      dockerfile: Dockerfile.client2
    container_name: client2
    depends_on:
      - client
    volumes:
      - ./client2:/app
    networks:
      default:
        aliases:
          - client2.local

networks:
  default:
    driver: bridge
