version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis.local

  beat:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "7777:7777"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - beat.local

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: client
    volumes:
      - ./client:/app
    networks:
      default:
        aliases:
          - client.local

networks:
  default:
    driver: bridge
